const category = {
  SNACK: 0,
  COFFEE: 1,
  PLANT: 2,
};

export const shoppingItems = [
  {
    id: 1,
    category: category.SNACK,
    image: "assets/images/sec1_1.jpeg",
    name: "아폴로 초콜릿",
    price: 2500,
  },
  {
    id: 2,
    category: category.SNACK,
    image: "assets/images/sec1_2.jpeg",
    name: "코코넛칩",
    price: 1500,
  },
  {
    id: 3,
    category: category.SNACK,
    image: "assets/images/sec1_3.jpeg",
    name: "쌀과자",
    price: 3200,
  },
  {
    id: 4,
    category: category.SNACK,
    image: "assets/images/sec1_4.jpeg",
    name: "홈런볼",
    price: 1500,
  },
  {
    id: 5,
    category: category.SNACK,
    image: "assets/images/sec1_5.jpeg",
    name: "포켓몬김",
    price: 8000,
  },
  {
    id: 6,
    category: category.COFFEE,
    image: "assets/images/sec2_1.jpeg",
    name: "폴바셋 시그니처 블렌드",
    price: 34900,
  },
  {
    id: 7,
    category: category.COFFEE,
    image: "assets/images/sec2_2.jpeg",
    name: "폴바셋 콜드브루 원액",
    price: 16000,
  },
  {
    id: 8,
    category: category.COFFEE,
    image: "assets/images/sec2_3.jpeg",
    name: "스타벅스 자몽 허니 블랙티",
    price: 6000,
  },
  {
    id: 9,
    category: category.COFFEE,
    image: "assets/images/sec2_4.jpeg",
    name: "공차 펄볶이?",
    price: 6000,
  },
  {
    id: 10,
    category: category.COFFEE,
    image: "assets/images/sec2_5.jpeg",
    name: "스벅 말차프라푸치노",
    price: 7000,
  },
  {
    id: 11,
    category: category.COFFEE,
    image: "assets/images/sec2_6.png",
    name: "레몬커피",
    price: 4800,
  },
  {
    id: 12,
    category: category.PLANT,
    image: "assets/images/sec3_1.jpeg",
    name: "피쉬본",
    price: 3500,
  },
  {
    id: 13,
    category: category.PLANT,
    image: "assets/images/sec3_2.jpeg",
    name: "틸란드시아",
    price: 800,
  },
  {
    id: 14,
    category: category.PLANT,
    image: "assets/images/sec3_3.jpeg",
    name: "선인장",
    price: 6000,
  },
];
